version: '3'
services:
  db:
    image: 'postgres'
    container_name: 'db'
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build: app/
    container_name: 'api'
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_NAME
      - API_HOST
      - DEBUG=True
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  spa:
    build: spa/
    container_name: 'spa'
    stdin_open: true
    tty: true

  web:
    image: nginx
    container_name: 'web'
    depends_on:
      - db
      - api
      - spa
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./static:/usr/share/nginx/static:ro
    ports:
      - 80:80

volumes:
  postgres_data:
